###########################
# Config applicative globale
###########################
# mode jar, port et context
server:
  port:                              ${PORT:9010}
  contextPath:                       /personnes-service


eureka:
  client:
    healthcheck:
      enabled: true